### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by wangjia184** [kwaclaw/KdSoft.Lmdb#3]
I use KdSoft.Lmdb with single-writer/multiple-reader case.
First I create `LmdbEnvironment` and a single thread use it to write to database, this is ok.
Then there are mutliple threads use the same `LmdbEnvironment` instance to create their own transaction to read from the database.

```
using (var tx = _env.BeginTransaction(TransactionModes.ReadOnly))
{
                ReadOnlySpan<byte> getData;
                tx.Commit();
}
```

However, `BeginTransaction` throw LmdbException 

> Transaction with same Id 12 exists already.

The reason is that,  `DbLib.mdb_txn_id()` in [here](https://github.com/kwaclaw/KdSoft.Lmdb/blob/df7e9b97506a45a96d057d307e4d9fda22e1e617/Lmdb/LmdbEnvironment.cs#L291) seems to be thread unsafe?

Then it raised that exception [here](https://github.com/kwaclaw/KdSoft.Lmdb/blob/df7e9b97506a45a96d057d307e4d9fda22e1e617/Lmdb/LmdbEnvironment.cs#L327)

Please KdSoft cannot be used in this way?  or is this a bug?

**Comment by kwaclaw** [comment]
Kdsoft.Lmdb just exposed the threading restrictions of the underlying Lmdb
library.

Have you tried to set the NoTheadLocalStorage option in the environment?

**Comment by kwaclaw** [comment]
Closing, no follow-up, no apparent issue.
