### ISSUE TITLE
Using the cursor with yield return.

### ISSUE THREAD

**Issue by panchow** [kwaclaw/KdSoft.Lmdb#4]
Hi, KDSoft.Lmdb is good stuff.  I'm trying it out and ran into a issue.

I wrote a method attempts to return an IEnumerable of items.

        public IEnumerable<TItem> GetAll()
        {
            using var transaction = _lmdbEnvironment.BeginReadOnlyTransaction();
            using var cursor = _lmdbDatabase.OpenCursor(transaction);
            var enumerator = cursor.Forward.GetEnumerator();
            while (enumerator.MoveNext())
            {
                yield return _serializer.Deserialize<TItem>(enumerator.Current.Data);
            }
            transaction.Commit();
        }

But I got a compile error:
Instance of type 'Cursor.ItemsEnumerator' cannot be used inside a nested function, query expression, iterator block or async method

public ref struct ItemsEnumerator
{
            public KeyDataPair Current { get; }
            public bool MoveNext();
}

I believe it is because the ItemsEnumerator is ref struct.  Do you have any suggestion how to support yield return?
Thank you.

**Comment by kwaclaw** [comment]
The reason for these special enumerators is to enable the use of foreach in
a fast allocation-free way.
It is based on the fact that foreach does not need an IEnumerable, but just
something that implements the same pattern.
See
https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable#remarks

But for your purpose you can also use the low level cursor operations like
GetNext();
Try this:

public IEnumerable<TItem> GetAll()
    {
        using var transaction = _lmdbEnvironment.BeginReadOnlyTransaction();
        using var cursor = _lmdbDatabase.OpenCursor(transaction);
        while (cursor.GetNext(out var entry)
        {
            yield return _serializer.Deserialize<TItem>(entry.Data);
        }
        transaction.Commit();
    }

Hope that helps.

Karl

**Comment by kwaclaw** [comment]
Explanation/advice provided.
